image:
  repository: 201009178507.dkr.ecr.us-west-2.amazonaws.com/services-multicd-mocks
  pullPolicy: IfNotPresent

nameOverride: "services-multicd-mocks"
fullnameOverride: "services-multicd-mocks"

labels:
  app: services-multicd-mocks
  service: services-multicd-mocks
  branch: devel
  version: devel
  protected_branch: "true"

default_branch: develop

deployment:
  replicaCount: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  terminationGracePeriodSeconds: 30
  restartPolicy: Always

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 1024Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  livenessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 90
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 90
    periodSeconds: 10

ingress:
  enabled: true
  paths: ["/"]
  hosts:
    - services-multicd-mocks.nubestaging.com
  tls: []
  ingressClassName: nginx-stg